### ISSUE TITLE
Error: Unable to access compilation with id = CompilationId(1) now. The compilation have been removed on the Rust side. The latest compilation id is CompilationId(112)

### ISSUE THREAD

**Issue by guillaume-docquier-vention** [rspack-contrib/ts-checker-rspack-plugin#13]
## Current behavior
Very rarely, I get the following error 
```
Rspack 1.1.3 compiled with 4 warnings in 91.77 s
[masked]/node_modules/@rspack/core/dist/index.js:2807
      (d) => __privateGet(this, _inner).addFileDependencies(d)
                                        ^

Error: Unable to access compilation with id = CompilationId(1) now. The compilation have been removed on the Rust side. The latest compilation id is CompilationId(112)
    at MergeCaller.callFn ([masked]/node_modules/@rspack/core/dist/index.js:2807:41)
    at MergeCaller.finalCall [as _onTimeout] ([masked]/node_modules/@rspack/core/dist/index.js:2672:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'GenericFailure'
}

Node.js v18.20.4
```

I seems like the compilation completed, but then I get an error.
I saw the error once locally and every now and then we get the error on the CI.

I saw the error when using [fork-ts-checker-webpack-plugin](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin) and I thought switching to the rspack very would help, but it didn't

## Expected behavior
The build completes without error.

## Steps to reproduce the issue
Unfortunately this is hard to reproduce, even for myself. I don't know how to debug this further.
I'm not even 100% sure that it is this plugin, but since compilation worked, I'm guessing it's a plugin that runs after the build?

## Issue reproduction repository
N/A

## Environment
I cannot share the full config because it is company owned.
What can I do to debug this further? I would think it might be `ts-checker-rspack-plugin` because it runs after the build, but I don't know how to validate this.

We use the following plugins:
- @rspack/core@1.1.3 (DefinePlugin, BannerPlugin)
- clean-webpack-plugin@4.0.0
- compression-webpack-plugin@11.1.0
- dotenv-webpack@8.1.0
- monaco-editor-webpack-plugin@7.1.0
- node-polyfill-webpack-plugin@4.0.0
- terser-webpack-plugin@5.3.10
- ts-checker-rspack-plugin@1.0.1

And run with:
```
mode: "production",
bail: true,
devtool: false,
```

System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 20.94 GB / 31.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.4/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
Browsers:
    Chrome: 130.0.6723.116
npmPackages:
    @rspack/cli: ^1.1.1 => 1.1.3 
    @rspack/core: ^1.1.1 => 1.1.3

**Comment by chenjiahan** [comment]
Bump `@rspack/core` to v1.1.5 should fix this.

See: https://github.com/rspack-contrib/ts-checker-rspack-plugin/issues/9

**Comment by guillaume-docquier-vention** [comment]
Thank you very much! I didn't think to look at `@rspack/core` :face_holding_back_tears:
