### ISSUE TITLE
Unable to access compilation with id = CompilationId and Error: write EPIPE 

### ISSUE THREAD

**Issue by felixmosh** [rspack-contrib/ts-checker-rspack-plugin#9]
## Current behavior
```
/Users/***/Projects/node/***/node_modules/@rspack/core/dist/index.js:2807
      (d) => __privateGet(this, _inner).addFileDependencies(d)
                                        ^

Error: Unable to access compilation with id = CompilationId(6) now. The compilation have been removed on the Rust side. The latest compilation id is CompilationId(7)
    at MergeCaller.callFn (/Users/***/Projects/node/***/node_modules/@rspack/core/dist/index.js:2807:41)
    at MergeCaller.finalCall [as _onTimeout] (/Users/***/Projects/node/***/node_modules/@rspack/core/dist/index.js:2672:12)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  code: 'GenericFailure'
}

Node.js v20.16.0
Error: write EPIPE
    at target._send (node:internal/child_process:879:20)
    at target.send (node:internal/child_process:752:19)
    at /Users/***/Projects/node/***/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/***/Projects/node/***/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/***/Projects/node/***/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/***/Projects/node/***/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:5:58) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```
After update rsbuild & ts-checker-rspack-plugin to latest versions, I'm getting on server bundle, this error every several HMR updates.
And the serve crushes after this error, which requires to kill the server and start serve again.

## Expected behavior
It should work properly

## Environment
 - **ts-checker-rspack-plugin**: 1.0.1
 - **@rsbuild/plugin-type-check**:1.1.0
 - **typescript**: 5.5.2
 - **@rspack/core**: 1.1.4
 - **@rsbuild/core**: 1.1.6
 - **os**: Macos

**Comment by SyMind** [comment]
@felixmosh Would you like to provide me with a minimal reproduction?

**Comment by SyMind** [comment]
@felixmosh I've released a canary version of Rspack. It would be great if you could give it a try. To use it, you can add the following overrides section in your package.json:

```json
"overrides": {
      "@rspack/core": "npm:@rspack/core-canary@1.1.5-canary-970ad72d-20241202111327"
}
```

**Comment by felixmosh** [comment]
Hi, thank you.
I'm using yarn berry, how should I use this `overrides` field?

**Comment by SyMind** [comment]
@felixmosh Using `resolutions` for yarn.

**Comment by felixmosh** [comment]
I've tried to add `"@rspack/core@npm:1.1.4": "npm:@rspack/core-canary@1.1.5-canary-970ad72d-20241202111327"` in resolutions, How can I ensure that I got the newer version?

**Comment by SyMind** [comment]
@felixmosh maybe you can check the yarn.lock.

**Comment by felixmosh** [comment]
It didn't updated it, so I guess it doesn't work

**Comment by SyMind** [comment]
@felixmosh Do you run `yarn install`? It is work for me.

**Comment by SyMind** [comment]
> I've tried to add `"@rspack/core@npm:1.1.4": "npm:@rspack/core-canary@1.1.5-canary-970ad72d-20241202111327"` in resolutions, How can I ensure that I got the newer version?

You should add

```
"resolutions": {
      "@rspack/core": "npm:@rspack/core-canary@1.1.5-canary-970ad72d-20241202111327"
}
```

**Comment by felixmosh** [comment]
It looks OK, didn't failed once :]

**Comment by chenjiahan** [comment]
Fixed: https://github.com/web-infra-dev/rspack/releases/tag/v1.1.5
